services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Configuration File for Traefik
      - ./traefik.yml:/etc/traefik/traefik.yml
  frontend:
    build: ./spa
    depends_on:
      - hits-counter
      - chat-websocket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatapp.rule=Host(`localhost`)"
      - "traefik.http.routers.chatapp.entrypoints=web"
    deploy:
      replicas: 2
  chat-websocket:
    build: ./chat-websocket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-ws.rule=Host(`localhost`) && PathPrefix(`/chat`)"
      - "traefik.http.routers.chat-ws.entrypoints=web"
      - "traefik.http.middlewares.chat-ws.stripprefix.prefixes=/chat"
      - "traefik.http.routers.chat-ws.middlewares=chat-ws"
    deploy:
      replicas: 3
  hits-counter:
    build: ./hits-counter
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hits.rule=Host(`localhost`) && Path(`/hits`)"
      - "traefik.http.routers.hits.entrypoints=web"
    deploy:
      replicas: 2
  redis:
    image: redis
